import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) throws IOException {
        FileWriter pw = new FileWriter("practa.txt", false);
        Scanner sc = new Scanner(System.in);
        System.out.print("Вы хотите прочитать рецепт моего любимого блюда??\n");
        System.out.print("1. Да\n2. Нет\n");
        int vibor = sc.nextInt();
        if (vibor == 1)
        {
            System.out.println("Рецепт моего любимого блюда: ");
            System.out.println("-------------------------------------------");
            System.out.println("Зайти в мак");
            pw.write("Рецепт моего любимого блюда: ");
            pw.write("\n");
            pw.write("-------------------------------------------");
            pw.write("\n");
            pw.write("Зайти в мак");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k);
            System.out.println("-------------------------------------------");
            System.out.println("Подойти к кассе самообслуживания");
            pw.append("Каллорий затрачено: " + k);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Подойти к кассе самообслуживания");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k1 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k1);
            System.out.println("-------------------------------------------");
            System.out.println("Нажать на вкладку морепродукты");
            pw.append("Каллорий затрачено: " + k1);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Нажать на вкладку морепродукты");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k2 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k2);
            System.out.println("-------------------------------------------");
            System.out.println("Выбрать 'Шримпролл'");
            pw.append("Каллорий затрачено: " + k2);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Выбрать 'Шримпролл'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k3 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k3);
            System.out.println("-------------------------------------------");
            System.out.println("Ткнуть на 'Среднее МакКомбо'");
            pw.append("Каллорий затрачено: " + k3);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Ткнуть на 'Среднее МакКомбо'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k4 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k4);
            System.out.println("-------------------------------------------");
            System.out.println("Выбрать 'Картошку фри'");
            pw.append("Каллорий затрачено: " + k4);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Выбрать 'Картошку фри'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k5 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k5);
            System.out.println("-------------------------------------------");
            System.out.println("Выбрать 'Выбрать соус терияки'");
            pw.append("Каллорий затрачено: " + k5);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Выбрать 'Выбрать соус терияки'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k6 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k6);
            System.out.println("-------------------------------------------");
            System.out.println("Выбрать 'Кока-колу без сахара'");
            pw.append("Каллорий затрачено: " + k6);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Выбрать 'Кока-колу без сахара'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k7 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k7);
            System.out.println("-------------------------------------------");
            System.out.println("Ткнуть на кнопочку 'Добавить в заказ'");
            pw.append("Каллорий затрачено: " + k7);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Ткнуть на кнопочку 'Добавить в заказ'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k8 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k8);
            System.out.println("-------------------------------------------");
            System.out.println("Ткнуть кнопку 'Оплата'");
            pw.append("Каллорий затрачено: " + k8);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Ткнуть кнопку 'Оплата'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k9 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k9);
            System.out.println("-------------------------------------------");
            System.out.println("Тапнуть кнопочку 'Подтвердить заказ'");
            pw.append("Каллорий затрачено: " + k9);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Тапнуть кнопочку 'Подтвердить заказ'");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k10 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k10);
            System.out.println("-------------------------------------------");
            System.out.println("Оплатить заказ и взять чек");
            pw.append("Каллорий затрачено: " + k10);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Оплатить заказ и взять чек");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k11 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k11);
            System.out.println("-------------------------------------------");
            System.out.println("Подождать, пока заказ готовиться");
            pw.append("Каллорий затрачено: " + k11);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Подождать, пока заказ готовиться");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k12 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k12);
            System.out.println("-------------------------------------------");
            System.out.println("Забрать заказ и сесть кушать");
            pw.append("Каллорий затрачено: " + k12);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Забрать заказ и сесть кушать");
            pw.write("\n");
            System.out.print("Введите кол-во затраченых каллорий: ");
            int k13 = sc.nextInt();
            System.out.println("Каллорий затрачено: " + k13);
            System.out.println("-------------------------------------------");
            System.out.println("Сидеть радостным кушать");
            pw.append("Каллорий затрачено: " + k13);
            pw.write("\n");
            pw.append("-------------------------------------------");
            pw.write("\n");
            pw.append("Сидеть радостным кушать");
            pw.write("\n");
            System.out.print("Введите кол-во полученных каллорий: ");
            int k14 = sc.nextInt();
            System.out.println("Каллорий получено: " + k14);
            pw.append("Каллорий получено: " + k14);
            pw.write("\n");
        }
        else
        {
            System.out.print("Блин, ладно(((");
        }
    }
}